# Generated by Django 4.2.2 on 2023-06-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantShopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='active',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='water',
        ),
        migrations.AlterField(
            model_name='category',
            name='light',
            field=models.CharField(max_length=50),
        ),
    ]
