# Generated by Django 4.2.2 on 2023-06-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantShopApp', '0002_rename_active_category_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='available',
        ),
        migrations.AddField(
            model_name='plant',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
