# Generated by Django 4.2.2 on 2023-08-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantShopApp', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
