# Generated by Django 4.2.2 on 2023-08-10 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantShopApp', '0007_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
