# Generated by Django 4.2.2 on 2023-08-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantShopApp', '0010_plantinshoppingcart_remove_saleitem_plant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='owner',
            new_name='cardHolder',
        ),
        migrations.AlterField(
            model_name='card',
            name='cardNumber',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expirationDate',
            field=models.DateField(max_length=5),
        ),
    ]
