# Generated by Django 4.2.2 on 2023-08-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantShopApp', '0011_rename_owner_card_cardholder_alter_card_cardnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirationDate',
            field=models.CharField(max_length=5),
        ),
    ]
